---
title: "Final Report: Structural Inductive Bias in Supervised Learning for Single-cell Data"
author:
- name: Elyas Heidari
  affiliation:
  - Department of Biological Systems Sciences and Engineering, ETH Zurich, Switzerland 
  - IMLS Institute for Molecular Life Sciences, University of Zurich, Switzerland
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
    toc_float: true
    number_sections: false
---
<!-- 2020-09-03 09:58 -->
<!-- elihei  [<eheidari@student.ethz.ch>]-->
<!--/Volumes/Projects/scGCN/analysis/04-final-report-GCN-2020-09-03.rmd-->

## Setup
```{r setup, include = FALSE}
library('BiocStyle')
knitr::opts_chunk$set(autodep=TRUE, cache=FALSE, dev='png', cache.lazy = FALSE)
# wflow_build(files='analysis/1-GCN_input_prep_pbmc.Rmd', view=F, verbose=T, delete_cache=F)
```

## Initialization and imports
```{r init_import}
set.seed(1996)
# imports
suppressMessages(source('R/dep.R'))
nice_cols_1   = c(
    "#DC050C", "#FF7F00", "#FDB462", 
    "#1965B0", "#7BAFDE", "#882E72", "#B2DF8A",  
    "#B17BA6", "#E7298A", "#E78AC3", "#33A02C", 
    "#55A1B1", "#8DD3C7", "#A6761D", "#E6AB02", "#7570B3", "#BEAED4")

nice_cols_2 = c("#666666", "#999999", "#aa8282", "#d4b7b7", "#8600bf", "#ba5ce3", 
    "#808000", "#aeae5c", "#1e90ff", "#00bfff", "#56ff0d", "#ffff00")
# initialization
data_input = 'data/data_input/pbmc'
data_tidy  = 'data/data_tidy/pbmc'
out_dir    = 'output/pbmc'
time_stamp = format(Sys.Date(), '%Y_%m_%d')
# dirs
## input data
adj1_f     = file.path(data_tidy, 'wi_adj_pbmc1_0.5_2021_01_10.txt')
adj2_f     = file.path(data_tidy, 'wi_adj_pbmc2_0.3_2021_01_10.txt')
comm_f    = file.path(data_tidy, 'gene_communities_pbmc1_0.5_2021_01_10.txt')
train_X_f = file.path(data_input, 'data_train.txt')
train_y_f = file.path(data_input, 'classes_train.txt')
test_X_f  = file.path(data_input, 'data_test.txt')
test_y_f  = file.path(data_input, 'classes_test.txt')

# 
MLP_f       = file.path(out_dir, 'importances/imp_MLP.txt')
GraphSAGE_f = file.path(out_dir, 'importances/imp_GraphSAGE.txt')
TransformerConv_f = file.path(out_dir, 'importances/imp_TransformerConv.txt')
## write
### plots
umap_out  = file.path(out_dir, sprintf('umaps/umaps_%s_%s.pdf', '%s', time_stamp))
graph_out = file.path(out_dir, sprintf('activations/graph_%s_%s.pdf', '%s', time_stamp))
comm_out  = file.path(out_dir, sprintf('communities/graph_comm_hc_%s_%s.pdf', '%s', time_stamp))
conf_out  = file.path(out_dir, sprintf('conf_%s_GCN.pdf', time_stamp))
```

## Load input data
```{r read, message=FALSE, warning=FALSE, paged.print=FALSE}
# data train
adj1       = adj1_f %>% fread %>% as.matrix 
adj1       = ifelse(abs(adj1) > 0.04, 1, 0)
adj2       = adj2_f %>% fread %>% as.matrix 
adj2       = ifelse(abs(adj2) > 0.05, 1, 0)
diff_genes = setdiff(colnames(adj1), colnames(adj2))
adj2 = cbind(adj2, matrix(0, nrow= nrow(adj2), ncol=length(diff_genes), dimnames=list(NULL,diff_genes)))
adj2 = rbind(adj2, matrix(0, nrow= length(diff_genes), ncol=ncol(adj2), dimnames=list(diff_genes,NULL)))
rownames(adj2) = colnames(adj2)
adj2 = adj2[colnames(adj1), colnames(adj1)]
train_X   = train_X_f %>% fread %>% as.matrix %>% t 
train_y   = train_y_f %>% fread  
test_X    = test_X_f %>% fread %>% as.matrix %>% t 
test_y    = test_y_f %>% fread  
colnames(train_X) = colnames(test_X) = colnames(adj1)

# grpah communities
graph_com = comm_f %>% fread %>% 
    .[, color := nice_cols_1[community]] %>%
    setkey(GENE) %>%
    .[colnames(adj1)]

# importance measures
imp_MLP = MLP_f %>% fread %>%
    setkey('V1') %>%
    .[colnames(adj1)] 

imp_MLP_mtx =  imp_MLP %>%
    .[, -c('V1')] %>%
    as.matrix %>%
    abs

imp_GraphSAGE = GraphSAGE_f %>% fread %>%
    setkey('V1') %>%
    .[colnames(adj1)] 
    
imp_GraphSAGE_mtx =  imp_GraphSAGE %>%
    .[, -c('V1')] %>%
    as.matrix %>%
    abs

imp_TransformerConv = TransformerConv_f %>% fread %>%
    setkey('V1') %>%
    .[colnames(adj1)] 
    
imp_TransformerConv_mtx =  imp_TransformerConv %>%
    .[, -c('V1')] %>%
    as.matrix %>%
    abs
```

## Graph Communities
```{r graph_com, message=FALSE, warning=FALSE, paged.print=FALSE}
graph_col_comm <- function(graph, lay, grp, sz, title=NULL, labels){
    igraph::V(graph)$color <- grp
    v <-  igraph::V(graph)
    sprintf(comm_out, title) %>% pdf()
    plot.igraph(
        graph,
        vertex.size = 6,
        layout = lay,
        vertex.label = labels,
        vertex.frame.color = igraph::V(graph)$color,
        vertex.label.family = 'Helvetica',
        vertex.label.dist = 0,
        vertex.label.cex = .25,
        vertex.label.font = .5,
        vertex.label.color = '#585c59',
        main=NULL)
    dev.off()
}

graph1  = graph_from_adjacency_matrix(adj1, 'undirected')
lay_nc1 = layout_nicely(graph1)
graph_col_comm(graph1, lay_nc1, graph_com$color, 5, title='PBMC 1', labels=graph_com$GENE)

graph2  = graph_from_adjacency_matrix(adj2, 'undirected')
lay_nc2 = layout_nicely(graph2)
graph_col_comm(graph2, lay_nc2, graph_com$color, 5, title='PBMC 2', labels=graph_com$GENE)
```

## Cell type average activations
```{r graphs, message=FALSE, warning=FALSE, paged.print=FALSE}
cell_type_graph <- function(type, title){
    sprintf(graph_out, paste0(title, '_train')) %>% pdf()
    train_idx = which(train_y$class_ == type)
    grp       = colMeans(train_X[train_idx,])
    grp = (grp - mean(grp))/sd(grp) 
    grp = grp + abs(min(grp))
    igraph::V(graph1)$color  = rgb(floor(255*(grp^(0.5))/max(grp^(0.5)*1.1)), floor(255*(grp^(0.5))/max(grp^(0.5)*1.1)), 0, maxColorValue=255, alpha=255)

    plot.igraph(graph1,
        vertex.size = 5,
        layout = lay_nc1,
        vertex.frame.color = igraph::V(graph1)$color,
        vertex.label = "",
        main=title)
    dev.off()
    sprintf(graph_out, paste0(title, '_test')) %>% pdf()
    test_idx = which(test_y$class_ == type)
    grp       = colMeans(test_X[test_idx,])
    grp = (grp - mean(grp))/sd(grp) 
    grp = grp + abs(min(grp))
    igraph::V(graph1)$color  = rgb(floor(255*(grp^(0.5))/max(grp^(0.5)*1.1)), floor(255*(grp^(0.5))/max(grp^(0.5)*1.1)), 0, maxColorValue=255, alpha=255)
    plot.igraph(graph1,
    vertex.size = 5,
    layout = lay_nc1,
    vertex.label = "",
    vertex.frame.color = igraph::V(graph1)$color)
    dev.off()
}

unique(train_y$class_) %>% map(~cell_type_graph(.x, .x))
```

## Cell type gene importances
```{r graphs, message=FALSE, warning=FALSE, paged.print=FALSE}
cell_type_graph_imp <- function(dataset, type, title){
    sprintf(graph_out, title) %>% pdf()
    grp       = dataset[, type]
    grp = (grp - mean(grp))/sd(grp) 
    grp = grp + abs(min(grp))
    igraph::V(graph1)$color  = rgb(floor(255*(grp^(0.7))/max(grp^(0.7)*1.1)), floor(255*(grp^(0.7))/max(grp^(0.7)*1.1)), 0, maxColorValue=255, alpha=255)
    plot.igraph(graph1,
        vertex.size = 5,
        layout = lay_nc1,
        vertex.frame.color = igraph::V(graph1)$color,
        vertex.label = "",
        main='')
    dev.off()
}

unique(train_y$class_) %>% map(~cell_type_graph_imp(imp_MLP_mtx, .x, paste0(.x, '_MLP')))
unique(train_y$class_) %>% map(~cell_type_graph_imp(imp_GraphSAGE_mtx, .x, paste0(.x, '_GraphSAGE')))
unique(train_y$class_) %>% map(~cell_type_graph_imp(imp_TransformerConv_mtx, .x, paste0(.x, '_TransformerConv')))
```

## Marker Genes
```{r graphs, message=FALSE, warning=FALSE, paged.print=FALSE}
markers_MLP = colnames(imp_MLP_mtx) %>% 
    map(~colnames(adj1)[order(imp_MLP_mtx[,.x], decreasing=TRUE)[1:5]]) %>% 
    setDT
names(markers_MLP) = colnames(imp_MLP_mtx)
markers_MLP

markers_GraphSAGE = colnames(imp_GraphSAGE_mtx) %>% 
    map(~colnames(adj1)[order(imp_GraphSAGE_mtx[,.x], decreasing=TRUE)[1:5]]) %>% 
    setDT
names(markers_GraphSAGE) = colnames(imp_GraphSAGE_mtx)
markers_GraphSAGE

markers_TransformerConv = colnames(imp_TransformerConv_mtx) %>% 
    map(~colnames(adj1)[order(imp_TransformerConv_mtx[,.x], decreasing=TRUE)[1:5]]) %>% 
    setDT
names(markers_TransformerConv) = colnames(imp_TransformerConv_mtx)
markers_TransformerConv
```

## UMAPs
```{r umaps, message=FALSE, warning=FALSE, paged.print=FALSE}
plot_umap <- function(mtx, cell_types, datasets, batches, title){
    umap_df = uwot::umap(mtx) 
    umap_dt = data.table(dataset=factor(datasets), 
                         cell_type=factor(cell_types), 
                         batch=factor(batches),
                         umap1=umap_df[,1], umap2=umap_df[,2]) 
    type_umap = umap_dt %>%
        ggplot +
        aes(umap1, umap2, color=cell_type, shape=dataset, size=dataset, pch=10, colour='black') +
        geom_point() +
        theme_bw() + 
        theme(axis.text= element_blank(), 
            axis.ticks.x=element_blank(),
            axis.ticks.y=element_blank(), 
            panel.grid.major = element_blank(), 
            panel.grid.minor = element_blank()) +
        scale_color_manual(values=nice_cols_1) +
        scale_shape_manual(values = c(1, 4)) +
        labs(title=title, x='UMAP1', y='UMAP2')
    batch_umap = umap_dt %>%
        ggplot +
        aes(umap1, umap2, color=batch, shape=dataset, size=dataset, pch=10) +
        geom_point() +
        theme_bw() + 
        theme(axis.text= element_blank(), 
            axis.ticks.x=element_blank(),
            axis.ticks.y=element_blank(),
            panel.grid.major = element_blank(), 
            panel.grid.minor = element_blank()) +
        scale_color_manual(values=nice_cols_2) +
        scale_shape_manual(values = c(1, 4)) +
        labs(title='', x='UMAP1', y='UMAP2')
    list(type=type_umap, batch=batch_umap)
}

raw_layer  = rbind(train_X, test_X)
# sub_idx    = sample(1:dim(raw_layer)[1], 10000)
sub_idx    = 1:dim(raw_layer)[1]
cell_types = c(train_y$class_, test_y$class_)[sub_idx]
batches    = c(train_y$Method, test_y$Method)[sub_idx]
datasets   = c(rep('training', dim(train_X)[1]), rep('test', dim(test_X)[1]))[sub_idx]

umap_raw   = plot_umap(raw_layer[sub_idx,], cell_types, datasets, batches, 'raw data')

TC_markers = c(unlist(markers_TransformerConv[1:2]))
umap_TC   = plot_umap(raw_layer[sub_idx, TC_markers], cell_types, datasets, batches, 'TranformerConv')

MLP_markers = c(unlist(markers_MLP[1:2]))
umap_MLP   = plot_umap(raw_layer[sub_idx, MLP_markers], cell_types, datasets, batches, 'MLP')

umap_plt    =  (umap_raw$type + umap_raw$batch) +
    plot_layout(guides = 'collect')
sprintf(umap_out, 'raw') %>% ggsave(umap_plt, filename=., width=15, height=7, device='pdf')

umap_plt    =  (umap_TC$type + umap_TC$batch) +
    plot_layout(guides = 'collect')
sprintf(umap_out, 'TC') %>% ggsave(umap_plt, filename=., width=15, height=7, device='pdf')

umap_plt    =  (umap_MLP$type + umap_MLP$batch) +
    plot_layout(guides = 'collect')
sprintf(umap_out, 'MLP') %>% ggsave(umap_plt, filename=., width=15, height=7, device='pdf')
```
